name: 'Get Playwright Version'
description: 'Get the Playwright Version from the project lockfile'
author: 'Atos'

branding:
  icon: 'at-sign'
  color: 'orange'

inputs:
  no-version-found:
    description: 'The message level when no Playwright version is found (error, warning, info)'
    required: false
    default: 'error'

outputs:
  playwright-version:
    description: The playwright version used in the project

runs:
  using: 'node20'
  main: 'dist/index.mjs'
