name: 'Get Playwright Version'
description: 'Get the Playwright Version from the project lockfile'

outputs:
  playwright-version:
    description: The playwright version used in the project

runs:
  using: 'node20'
  main: 'index.js'
